export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CALENDAR_CANCEL = 'CALENDAR_CANCEL';
export const CALENDAR_CONFIRM = 'CALENDAR_CONFIRM';
export const OPEN_CALENDAR = 'OPEN_CALENDAR';
export const DISPLAY_OPTION = 'DISPLAY_CHART';
export const DETAIL_SPECIFIC_DATE = 'DETAIL_SPECIFIC_DATE';
